### ISSUE TITLE
?????

### ISSUE THREAD

**Issue by thefakeschool** [new92/IGFollowersIncreaser#9]
Wtf i dont understand
![image](https://user-images.githubusercontent.com/128187335/230791458-b648d1e6-9761-45ba-8580-a467eac0c14e.png)

**Comment by thefakeschool** [comment]
Windows 10. V3

**Comment by new92** [comment]
Hey there, first things first thank you for mentioning this bug. So whenever there is the error message: `challenge_required` it means that you need to login manually to your account in order for the Instagram to verify that the specific account is being ran by a human. So in order to fix it you need to login manually to your Instagram account, do any verification that asks you and run the script again. I suggest you tho, when this error occurs to then after you're done with the verification, to run the script after 3 days in order for your account not to get suspended. Hope this helped
